#!/bin/bash
#
# Description: This script runs before the commit message editor opens to prepare or modify the commit message file.
#
# Copyright (c) 2025 honeok <i@honeok.com>
#
# SPDX-License-Identifier: GPL-2.0-only

# Installation:
# 1. Copy to .git/hooks/prepare-commit-msg

COMMIT_MSG_FILE="$1"
COMMIT_SOURCE="$2"

case "$COMMIT_SOURCE" in
    merge | squash | rebase | template | commit ) exit 0 ;;
esac

SOB="$(git var GIT_COMMITTER_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')"
git interpret-trailers --in-place --trailer "$SOB" "$COMMIT_MSG_FILE"