---
name: "Build nginx"

on:
  push:
    branches: [master, release]
    paths:
      - "lnmp/nginx/**"
      - "!lnmp/nginx/**/*.md"
      - ".github/workflows/build-nginx.yml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "lnmp/nginx/**"
      - "!lnmp/nginx/**/*.md"
      - ".github/workflows/build-nginx.yml"
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  WORK_DIR: lnmp/nginx
  DOCKERHUB_REPO: ${{ secrets.DOCKER_USERNAME || github.repository_owner }}/nginx

jobs:
  check:
    name: "Pre check"
    runs-on: ubuntu-latest
    outputs:
      renew: ${{ steps.vers.outputs.renew }}
      nginx_version: ${{ steps.vers.outputs.nginx_version }}
      zstd_version: ${{ steps.vers.outputs.zstd_version }}
      headers_more_version: ${{ steps.vers.outputs.headers_more_version }}
      geoip2_version: ${{ steps.vers.outputs.geoip2_version }}

    steps:
      - name: "Resolve upstream versions"
        id: vers
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -eEuo pipefail

          RENEW="false"
          LATEST_VER="$(gh api 'repos/nginx/nginx/tags?per_page=100' --jq '.[].name' | sed -nE 's#^release-([0-9]+\.[0-9]+\.[0-9]+)$#\1#p' | sort -V | tail -n 1)"
          LATEST_IMG_VER="$(docker run --rm nginx:${LATEST_VER}-alpine sh -c "nginx -v 2>&1" 2>/dev/null | awk -F'[/ ]' '{print $NF}' || true)"
          CURRENT_VER="$(skopeo list-tags "docker://docker.io/$DOCKERHUB_REPO" 2>/dev/null | jq -r '.Tags[]' | grep -oP '(?<![0-9.])1\.\d{1,2}\.\d{1,2}(?![0-9.])' | sort -uV | tail -n1 || true)"
          ZSTD_VERSION="$(gh release view -R facebook/zstd --json tagName -q .tagName | sed 's#v##')"
          HEADERS_MORE_VERSION="$(gh api 'repos/openresty/headers-more-nginx-module/tags?per_page=100' --jq '.[].name' | sed 's#^v##' | grep -E '^[0-9]+(\.[0-9]+){1,2}$' | sort -V | tail -1)"
          GEOIP2_VERSION="$(gh api 'repos/leev/ngx_http_geoip2_module/tags?per_page=100' --jq '.[].name' | grep -E '^v?[0-9]+(\.[0-9]+){1,2}$' | sort -V | tail -1)"

          if [[ "$(printf '%s\n%s\n' "$LATEST_VER" "$CURRENT_VER" | sort -V | head -n 1)" != "$LATEST_VER" && "$LATEST_VER" == "$LATEST_IMG_VER" ]] || [[ -z "$CURRENT_VER" && "$LATEST_VER" == "$LATEST_IMG_VER" ]]; then
            echo "Build required."
            RENEW="true"
          else
            echo "Build skipped."
          fi

          echo "renew=${RENEW}" >> "$GITHUB_OUTPUT"
          echo "nginx_version=$LATEST_VER" >> "$GITHUB_OUTPUT"
          echo "zstd_version=$ZSTD_VERSION" >> "$GITHUB_OUTPUT"
          echo "headers_more_version=$HEADERS_MORE_VERSION" >> "$GITHUB_OUTPUT"
          echo "geoip2_version=$GEOIP2_VERSION" >> "$GITHUB_OUTPUT"

  build:
    name: "Build image"
    needs: [check]
    if: needs.check.outputs.renew == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
    strategy:
      fail-fast: true
      matrix:
        include:
          - { os: ubuntu-24.04, platform: linux/amd64 }
          - { os: ubuntu-24.04-arm, platform: linux/arm64 }
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Set platform pair"
        run: |
          PLATFORM_PAIR=$(awk -F/ '{print $1"-"$2$3}' <<< "${{ matrix.platform }}")
          echo "PLATFORM_PAIR=$PLATFORM_PAIR" >> "$GITHUB_ENV"

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v4

      - name: "Login to DockerHub"
        uses: docker/login-action@v4
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Docker metadata"
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: |
            type=raw,value=alpine
            type=raw,value=${{ needs.check.outputs.nginx_version }}-alpine
          labels: |
            org.opencontainers.image.title=nginx
            org.opencontainers.image.description=nginx is an HTTP web server, reverse proxy, content cache, load balancer, TCP/UDP proxy server, and mail proxy server.
            org.opencontainers.image.url=https://nginx.org
            org.opencontainers.image.source=https://github.com/nginx/nginx
            org.opencontainers.image.version=${{ needs.check.outputs.nginx_version }}
            org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
            org.opencontainers.image.licenses=BSD-2-Clause

      - name: "Build and export"
        id: build
        uses: docker/build-push-action@v7
        with:
          context: ${{ env.WORK_DIR }}
          platforms: ${{ matrix.platform }}
          build-args: |
            NGINX_VERSION=${{ needs.check.outputs.nginx_version }}
            ZSTD_VERSION=${{ needs.check.outputs.zstd_version }}
            HEADERS_MORE_VERSION=${{ needs.check.outputs.headers_more_version }}
            GEOIP2_VERSION=${{ needs.check.outputs.geoip2_version }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.DOCKERHUB_REPO }},push-by-digest=${{ github.ref_name == 'master' }},name-canonical=${{ github.ref_name == 'master' }},push=${{ github.ref_name == 'master' }}

      - name: "Export digest"
        if: ${{ github.ref_name == 'master' }}
        run: |
          rm -rf /tmp/digests
          mkdir -p /tmp/digests
          digest=${{ steps.build.outputs.digest }}
          touch /tmp/digests/${digest#sha256:}

      - name: "Upload artifact"
        if: ${{ github.ref_name == 'master' }}
        uses: actions/upload-artifact@v7
        with:
          name: digest-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: "Merge manifest"
    needs: [check, build]
    if: github.ref_name == 'master' && needs.check.outputs.renew == 'true' && needs.build.result == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: "Download digests"
        uses: actions/download-artifact@v8
        with:
          path: /tmp/digests
          pattern: digest-*
          merge-multiple: true

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v4

      - name: "Login to DockerHub"
        uses: docker/login-action@v4
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Docker metadata"
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: |
            type=raw,value=alpine
            type=raw,value=${{ needs.check.outputs.nginx_version }}-alpine
          labels: |
            org.opencontainers.image.title=nginx
            org.opencontainers.image.description=nginx is an HTTP web server, reverse proxy, content cache, load balancer, TCP/UDP proxy server, and mail proxy server.
            org.opencontainers.image.url=https://nginx.org
            org.opencontainers.image.source=https://github.com/nginx/nginx
            org.opencontainers.image.version=${{ needs.check.outputs.nginx_version }}
            org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
            org.opencontainers.image.licenses=BSD-2-Clause

      - name: "Create manifest list and push"
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.DOCKERHUB_REPO }}@sha256:%s ' *)

      - name: "Inspect image"
        run: docker buildx imagetools inspect ${{ env.DOCKERHUB_REPO }}:${{ needs.check.outputs.nginx_version }}-alpine

  sync:
    name: "Sync readme to dockerhub"
    needs: [merge]
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Sync readme to dockerhub"
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKERHUB_REPO }}
          readme-filepath: ${{ env.WORK_DIR }}/README.md
          enable-url-completion: false
