name: CI

on:
  push:
    branches:
      - master
    paths:
      - '*.sh'
      - '**/*.sh'
  pull_request:
    paths:
      - '*.sh'
      - '**/*.sh'
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          files: '**/*.sh'
          ignore_paths: >-
            docker/install.sh