name: 'Build DanmakuRender image'

on:
  workflow_dispatch:

jobs:
  build:
    name: 'Build DanmakuRender image'
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: 'Get DanmakuRender default branch'
        run: |
          REMOTE_BRANCH=$(curl -fsSL "https://api.github.com/repos/SmallPeaches/DanmakuRender" | jq -r '.default_branch')
          echo "REMOTE_BRANCH=${REMOTE_BRANCH}" >> $GITHUB_ENV

      - name: 'Set up Docker QEMU'
        uses: docker/setup-qemu-action@v3.5.0

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3.10.0

      - name: 'Login to DockerHub'
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'Build and push DanmakuRender image'
        uses: docker/build-push-action@v6.11.0
        with:
          context: "{{ defaultContext }}:fun/DanmakuRender"
          file: Dockerfile
          push: true
          tags: |
            "${{ env.DOCKER_USERNAME }}/danmakurender:${{ env.REMOTE_BRANCH }}"
            "${{ env.DOCKER_USERNAME }}/danmakurender:latest"
          platforms: linux/amd64, linux/arm64/v8