name: Docker install Script sync

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v4.1.6

      - name: Download and compare get-docker.sh
        run: |
          curl -fsSkL -o "get-docker.sh" https://get.docker.com
          if ! cmp -s docker/install.sh get-docker.sh; then
            mv -f get-docker.sh docker/install.sh
            echo "changed=true" >> $GITHUB_ENV
          else
            rm -f get-docker.sh
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Upload to repository
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        if: ${{ env.changed == 'true' }}
        with:
          commit_message: "chore: docker install script sync by Github Actions 🤖"

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: "cancelled, skipped"