name: 'Build Kms image'

on:
  workflow_dispatch:

jobs:
  build:
    name: 'Build Kms image'
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: 'Set up Docker QEMU'
        uses: docker/setup-qemu-action@v3.5.0

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3.10.0

      - name: 'Login to DockerHub'
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'Build and push Kms image'
        uses: docker/build-push-action@v6.11.0
        with:
          context: "{{ defaultContext }}:fun/kms"
          file: Dockerfile
          push: true
          tags: "${{ env.DOCKER_USERNAME }}/kms:latest"
          platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/riscv64, linux/s390x