name: Publish PHP74 Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push PHP image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ldnmp/php/Dockerfile_7.4
          push: true
          tags: |
            honeok/php:7.4.33-fpm-alpine3.16
            honeok/php:7.4-fpm-alpine
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
