---
name: "Run shellcheck"

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  shellcheck:
    name: "Run shellcheck"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Run shellcheck"
        uses: ludeeus/action-shellcheck@master
